name: playnova
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # UI & Utilities
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.1 # State management ke liye best hai
  
flutter:
  uses-material-design: true
  
